//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2018 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------

package com.pdftron.android.pdfnetsdksamples;

import java.util.ArrayList;

public abstract class PDFNetSample {
    
    /*
     * Path in assets folder where the input files are stored.
     */
    protected static final String INPUT_PATH = "TestFiles/";
    protected static final String OFFICE_FOLDER_NAME = "DocxFiles";
    
    /*
     * Title used to identify the sample in the detail fragment.
     */
    private String mTitle;
    
    /*
     * Sample description shown in the detail fragment.
     */
    private String mDescription;
    
    /*
     * Stores the files that were generated by the sample.
     */
    protected ArrayList<String> mFileList;
    
    /*
     * Indicates that this sample is enabled so it can be executed.
     */
    private Boolean mEnabled;
    
    public PDFNetSample() {
        this.mTitle = "{Sample Title}";
        this.mDescription = "{Sample Description}";
        this.mFileList = new ArrayList<String>();
        this.mEnabled = true;
    }
    
    public void run(OutputListener outputListener) {
        this.mFileList.clear();
    };
    
    protected void setTitle(String title) {
        this.mTitle = title;
    }
    
    protected void setTitle(int resId) {
        this.mTitle = MiscellaneousSamplesApplication.getInstance().getString(resId);
    }
    
    public String getTitle() {
        return this.mTitle;
    }
    
    protected void setDescription(String description) {
        this.mDescription = description;
    }
    
    protected void setDescription(int resId) {
        this.mDescription = MiscellaneousSamplesApplication.getInstance().getString(resId);
    }
    
    public String getDescription() {
        return this.mDescription;
    }
    
    public ArrayList<String> getFiles() {
        return this.mFileList;
    }
    
    protected void addToFileList(String fileName) {
        this.mFileList.add(fileName);
    }
    
    protected void printHeader(OutputListener outputListener) {
        String header = MiscellaneousSamplesApplication.getInstance().getString(R.string.str_running_sample_header, this.mTitle);
        outputListener.println(header + "\n");
    }
    
    protected void printFooter(OutputListener outputListener) {
        String footer = MiscellaneousSamplesApplication.getInstance().getString(R.string.str_running_sample_footer);
        outputListener.println("\n" + footer);
        outputListener.println("--------------------");
    }
    
    protected void EnableRun() {
        this.mEnabled = true;
    }
    
    protected void DisableRun() {
        this.mEnabled = false;
    }
    
    protected Boolean isEnabled() {
        return this.mEnabled;
    }
    
    /**
     * This will be used by ArrayAdapter when creating the list of PDFNetSamples.
     */
    @Override
    public String toString() {
        return this.mTitle;
    }
}
